esphome:
  name: tv-light-1

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "foobar"

ota:
  - platform: esphome
    id: my_ota
    password: "foobar"  

wifi:
  ssid: "adamkis"
  password: "KonadrAA"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TV-ligth-1"
    password: "PjM5wL45BzxI"

captive_portal:

            
# Binary input on D5 (GPIO14)
binary_sensor:
  - platform: gpio
    pin: D5
    name: "USB tracker"
    id: binary_input
    on_press:
      then:
        - switch.turn_on: output
    on_release:
      then:
        - switch.turn_off: output

# Output on GPIO02
switch:
  - platform: gpio
    pin: GPIO02
    id: output
    name: "LED light"

#switch:
#  - platform: output
#    name: "Generic Output"
#    output: 'generic_out'
#    id: sw


    